### ISSUE TITLE
Add linter for JS style enforcement

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#106]
Maybe something like https://github.com/palantir/tslint

This could be made easier if the server-side stuff was typescript as well (see #105)

**Comment by toddmedema** [comment]
Agreed - AirBnB also publishes a nice JS style guide including the lint flags: https://github.com/airbnb/javascript

(note for us, for comments, they recommend doing multi-line format for all multi-line comments)

**Comment by smartin015** [comment]
This is now done.
