### ISSUE TITLE
Have "Validation errors" button jump to & flash first error line

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#107]
It's one thing to tell users there's an error somewhere in their file, it's another (more useful) thing to give them an easy way to jump to 'em :)

**Comment by toddmedema** [comment]
@smartin015 idea / question here - should we flag `TODO` (or `TODO:`?) as an error? As I'm writing this quest, think it'd actually be really handy to make it easy for creators to speedily create an outline with TODO's, then go back and find & fill them in

**Comment by smartin015** [comment]
I think that might be more of a warning-level sort of issue. It's less of a logical or syntactical problem than an unfinished issue they should be aware of... especially if it's in a comment.

**Comment by smartin015** [comment]
Backlogging for now

**Comment by smartin015** [comment]
Done!
