### ISSUE TITLE
Cleanup: Programmatic error messages

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#111]
*Migrated to expeditionrpg/expedition#279 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Instead of having to write

`log.err('combat card has no enemies listed', '414');`

We could instead import errors/definitions/414.tsx and pass it through to log.err(). This saves the text and error number duplication, and we could potentially use the other error fields later on without having to plumb them through all the existing errors.

**Comment by toddmedema** [comment]
I was thinking the same thing :-) the only thing I'd add is that we sometimes still want custom error messages, ie when the error includes the line text. So perhaps log.error(number, optional error text) - or perhaps log.error(number, line string), and then the error name can optionally include the line string via a find-and-replace

**Comment by smartin015** [comment]
Backlogging this cleanup for now.
