### ISSUE TITLE
Ops: Support for relative operators

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#114]
ie `gold -= 10` - gets me every time.

Or, throw an error (right now it fails silently). But, something tells me it'd be about the same amount of work to detect and error vs make it work, so I'd be in favor of making it work :) @smartin015

**Comment by smartin015** [comment]
Throwing errors we might get for free with error reporting by #68

Modifying the expression could get complicated, though. We'd need an airtight regexp.

**Comment by toddmedema** [comment]
Throwing this in here too - looks like `a == true && b = true` doesn't work, but `a == true & b == true` does (single ampersand). Same with `||`

That's weird / non-standard / also fails silently. 

Well, technically it's just using bitwise ops instead of logical ops - but if we have to use the word "bitwise" in documentation about how to write a quest, we're failing as designers lol

**Comment by smartin015** [comment]
"or" and "and" are also valid. I'd suggest we recommend those as the primary option for boolean comparisons.

**Comment by toddmedema** [comment]
Dropped an issue on MathJS https://github.com/josdejong/mathjs/issues/843
