### ISSUE TITLE
(ongoing) New icons request list

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#116]
*Migrated to expeditionrpg/expedition#280 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

- food
- gold / coin / money
- gem
- treasure chest

When added, new icons should be Expedition-ified (aka apply the Expedition brush to the vector in Illustrator)

**Comment by danielwiktorczyk** [comment]
Even the compass logo would work great as an available icon!

**Comment by toddmedema** [comment]
Also a timer or clock

**Comment by toddmedema** [comment]
Adding clock / compass icon here: https://github.com/ExpeditionRPG/expedition-app/pull/308
(should make its way into the Quest Creator by this weekend)

**Comment by smartin015** [comment]
Backlogging.
