### ISSUE TITLE
"on surge" events

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#119]
We should let the user override surges. Users may wish to have text before a surge, during it (overriding the default surge text), or after it, so we may need three events (on beforeSurge, onSurge, onAfterSurge, for example).

This will also require modifying the app and XML language to accept these new overrides.

**Comment by toddmedema** [comment]
I like the on before/after vs on surge as a way to differentiate if they're trying to override the default, and also specify order of operations

**Comment by smartin015** [comment]
Backlogging.

**Comment by toddmedema** [comment]
This is now available via `* on round`
