### ISSUE TITLE
Conditionally applied paragraphs

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#125]
Here's how we currently have to conditionally hide paragraphs within a roleplay card:

```markdown
_Roleplay Card_

Some text (always shown)

{{(someCondition) ? "Conditional text" : ""}}
```

This starts to look weird when the conditional text is relatively long and begins wrapping the editor.

Instead, we could do this in the intuitive way:

```markdown
_Roleplay Card_

Some text (always shown)

{{someCondition}} Conditional text
```

Basically, check the start of each paragraph for an op section. If the op has some result and the result is boolean, show or hide the text if it's true or false, respectively.

**Comment by toddmedema** [comment]
That makes sense. Test case we'd want to watch for is if there's an op at the start that outputs something besides a boolean, ie
```
_card_

{{dayCount}} days later...
```

Added to [far future](https://github.com/Fabricate-IO/expedition-quest-creator/issues/27): typing ops variables, ie if a user sets dayCount to a number at first and expects it to be a number, it'd be bad it if accidentally got set to a boolean (which'd then cause the above sentence to sometimes disappear!)

**Comment by smartin015** [comment]
Backlogging.

**Comment by smartin015** [comment]
Done!
