### ISSUE TITLE
Ctrl+Z behavior on collaborative editing

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#126]
I believe what's happening is the undo operation is jumping the cursor to the last inserted text. This text can be a collaborative edit from another computer, and not your own, which can jump the screen and  make it difficult to undo multiple times.

**Comment by toddmedema** [comment]
Hmm. Seems related to https://github.com/Fabricate-IO/expedition-quest-creator/issues/133 - though, they seem like they'll have two different solutions

**Comment by smartin015** [comment]
Dupe of #133
