### ISSUE TITLE
Fix Control+Z Behavior

### ISSUE THREAD

**Issue by danielwiktorczyk** [ExpeditionRPG/expedition-quest-creator#133]
When entering a new session for editing a quest (so that there are no edits to undo yet), inputting Cntrl+Z sends the quest design page into an "unsaved quest" with the `line 1 Loading...`indefinitely. Afterward, opening up the `.quest` file will lead to the same `Loading...` line with no changes. 

(had to copy the old .quest file's text into a fresh new project)
<img width="713" alt="loadingerror" src="https://cloud.githubusercontent.com/assets/24488852/21747668/a37a15fa-d53c-11e6-8d43-e380448af8f9.png">

**Comment by toddmedema** [comment]
That's no good! Adding this to our current reliability / stability coding sprint

**Comment by toddmedema** [comment]
Some initial research here, looks like Ace has an UndoManager, and calling .reset() on it /should/ prevent the user from going back to before the quest was inserted...but, can't seem to find it / access it from the TextView class. More work required: https://ace.c9.io/api/undomanager.html

**Comment by smartin015** [comment]
Bumping this to high impact. This has been a recurrent problem for shared quest writing
