### ISSUE TITLE
Allow local DB instance via container / travis for testing

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#136]
Now that we have [containerizer](https://github.com/Fabricate-IO/containerizer), we can create a local SQL DB for development. This might also prove useful in testing the model code in unit tests as well. (ie for travis CI)

**Comment by toddmedema** [comment]
This is especially important / useful in doing more complete testing for models, for example that inserting and deleting works, but also against potential security vulnerabilities

**Comment by toddmedema** [comment]
Note: may not be feasible to do in-memory / quick postgres testing in CI

**Comment by smartin015** [comment]
Infeasible to have inmemory testing with *just* postgres, but if we use an ORM (#258) then we could do this a lot more easily. Backlogging for now.

**Comment by toddmedema** [comment]
Been thinking about this - wonder if we should split out the API to a separate service / repo from the Quest Creator UI before starting down this road, otherwise it's going to get harder and harder to split them out in the future

**Comment by smartin015** [comment]
I think that's something that needs to be done, but I don't think it's necessarily harder to split after implementing an ORM. We don't have any dependencies between the FE code and the server, apart from web calls, right?

**Comment by toddmedema** [comment]
Fair, it might take a bit longer to de-tangle packages and testing / travis configurations, but probs won't be too bad

**Comment by smartin015** [comment]
Done! inmemory postgresql via sequelize.
