### ISSUE TITLE
Publishing same quest doc by two users publishes twice

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#147]
We should keep track of which user publishes the quest (for auditability), but we shouldn't show both quests at once. We could SELECT UNIQUE on the ID column, but AFAIK it's a combination of user ID and quest ID.

**Comment by toddmedema** [comment]
@smartin015 yep, it's userId + '_' + docId. Do you remember what the reasoning for that was? Given this bug, I'd be inclined to make it just docId, but want to make sure we anticipate any challenges - https://github.com/Fabricate-IO/expedition-quest-creator/blob/master/models/quest.js#L178

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-quest-creator/pull/223
