### ISSUE TITLE
Ability to "favorite" quests (or rate?)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#150]
TODO: research platforms and best practices around ratings / search / tagging / aggregation

And then, in search, the ability to search through only favorited quests

How would we handle this on the back end? Separate user_favorites table?

Thought: what if we skipped this and went straight to ratings, and then had a ratings-based search?

**Comment by smartin015** [comment]
Closing this out (should be in the app)
