### ISSUE TITLE
Catch encoding errors, and support for non-latin1 characters

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#157]
Re-producible with smart quote characters: `’`

There are also many other useful characters outside of that character range (such as ✓)

Got
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at i (http://quests.expeditiongame.com/bundle.js:17:25214)
```

Not only did it error, but that error didn't get passed to the saving indicator - just say there saying "saving..."

Possibility: encode when saving and loading: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa

Will need to make sure that the app is able to handle it properly (both in the quest editor, and after publishing)

**Comment by smartin015** [comment]
&geq has worked fine in the past... there's also escaped code for other characters. Agreed that it would be nice though.

It sounds like this is actually two bugs - failure to catch the exception, and adding encoding support.
