### ISSUE TITLE
Advertise collaborative editing

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#174]
We should show this off a bit (and load test it at some point.... massive collaborative quest party?)

* Could have a blurb or example on the home page
* Could describe collab editing in our help docs
* Could indicate the number of people writing a quest

**Comment by toddmedema** [comment]
Before we do this, might be good to figure out the bug where quest publishing isn't synced (ie two people can publish two different copies of the same quest)

**Comment by toddmedema** [comment]
Closed - added to feature highlights on homepage
