### ISSUE TITLE
Joi validation in routes, normalize, other files

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#183]
Replace its existing use in Constants, TextView / Spellcheck and Normalize: https://github.com/Fabricate-IO/expedition-quest-creator/pull/182/files/6d61118507e1a61b7d3728ce480d0a419713ec5c#diff-872cc6af2279153e45c07d23a9249a1c

We can likely replace most (if not all) of the normalize code with a single call to Joi.validate once we've built the new schema

Can then also integrate with routes.js

**Comment by smartin015** [comment]
Backlogging.

**Comment by toddmedema** [comment]
No longer relevant in quest creator + replaced by QDL validation tech
