### ISSUE TITLE
Monitor API 500 errors, abstract try/catches in code

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#186]

**Comment by smartin015** [comment]
We shouldn't be relying on users telling us when stuff breaks :(

**Comment by toddmedema** [comment]
For the monitoring side of things, new relic should notify us now. Perhaps we should cause a controlled server failure to make sure?

**Comment by toddmedema** [comment]
Closing, subsumed by https://github.com/ExpeditionRPG/expedition-quest-creator/issues/266
