### ISSUE TITLE
Routes.js - abstract auth check to middleware

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#189]
*Migrated to expeditionrpg/expedition#289 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

aka find a good existing auth middleware
note that auth and how its passed seems to vary between quest creator and app, and between web / Android / iOS. Aka, test really thoroughly!

**Comment by smartin015** [comment]
Backlogging.
