### ISSUE TITLE
Complete unit tests

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#191]
Likely requires upgrading typescript, webpack, etc to match app versions

Following the way the app does it, use Karma for tests to run webpack and emulate a browser, so that we can actually run tests against things that require `import` statements, `window` objects, etc (for example, Spellcheck)

**Comment by smartin015** [comment]
Karma is set up - and this bug would be better as a global "have unit tests implemented" style thingy.

**Comment by smartin015** [comment]
Includes #184

**Comment by smartin015** [comment]
New policy: if we're working on a file that has incomplete tests, implement at least one in the PR. Closing this out for now.
