### ISSUE TITLE
Move shared QDL constants to app

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#192]
@smartin015 thoughts?

For example, quest metadata and regexes are now getting duplicated across both the app and quest creator - besides duplicate code itself, that would also (at least ideally, hah) result in duplicate tests.

Might also simplify / unify logic around things like parsing and cleaning.

Long term vision being other versions of the app (such as the NES port that just came out, or an online-only version of the game for long-distance multiplayer), where having shared pieces of code would also be quite helpful.

Con: having more repos = a bit more of a headache when rolling out changes

**Comment by smartin015** [comment]
We *could* do a separate repo, or we could just make sure all shared variables are listed in the app repo (since that's a strong dependency of the quest IDE). I'd prefer the latter for now, since it means we don't need to track a third repository.

**Comment by smartin015** [comment]
Backlogging until this becomes a problem.

**Comment by smartin015** [comment]
I thiiiink we did this already.
