### ISSUE TITLE
Make design less intimidating to non-coders

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#206]
*Migrated to expeditionrpg/expedition#291 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Some specific suggestions we've received:

- use a non-monospace font for text blocks
- default to a "light" theme (aka dark text on a light background, like the app)

v2: graph-based interface

**Comment by smartin015** [comment]
From a previous bug:
We can use a dot graph, where each node of the graph is a base level block with a known ID. This limits the number of convoluted goto actions to base-level elements only, which may make debugging things a lot easier in practice. This requires the DFS code to draw edges between IDs, though.

**Comment by smartin015** [comment]
backlogging.
