### ISSUE TITLE
Combat duration / round trigger

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#215]
Incentivize players to act quickly (ie fighting in a burning building, etc)

could add _.lastCombatDuration, or, more flexible, have an `* on round` optional trigger that could increment your own variables and show text. If there's no text (ie just ops), shouldn't be shown to user

**Comment by smartin015** [comment]
Backlogging for now.

**Comment by smartin015** [comment]
Wontfix.
