### ISSUE TITLE
Improvement ideas based on Twine

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#22]
Open source choose-your-own-adventure crafter: https://twinery.org/ and their guide http://twinery.org/wiki/twine2:guide

Ideas from it:
- ability to debug the quest starting from any node
- adding a choice to a card automatically generates the nested node that that choice points to
  - the name of that node (on first generation, not editing) is auto-filled with the choice text
- support for formatting text: (or do we already have this?) http://twinery.org/wiki/twine2:how_to_format_text
- idea for random event syntax: http://twinery.org/wiki/twine2:add_stats_rpg_battles_or_just_plain_random_events
- adding images and sound idea: http://twinery.org/wiki/twine2:add_an_image_movie_sound_effect_or_music

Also, their graph view in general makes it much easier to reason about and follow story progression

**Comment by smartin015** [comment]
Had a recent chat with a quest creator - they used a [dot graph](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) to stage their ideas. Each node of the graph is a base level block with a known ID. This limits the number of convoluted goto actions to base-level elements only, which may make debugging things a lot easier in practice.

**Comment by smartin015** [comment]
Most of these we've done! Moved images/sound request to #229, dot graph stuff to #206.
