### ISSUE TITLE
Refactor DB models: improved model metadata `table` dictionary

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#220]
From https://github.com/ExpeditionRPG/expedition-quest-creator/pull/210/files/69a546290c6860eac13c5ffbb952fb3f76a8a122#diff-10106da5bd15e9f107babe5542495a57

Make the local `const table = {name: 'feedback', id: ['id']}` , which would also make it easy to expand to future meta attributes.

(primarily to eliminate the need to pass id as a separate value to the `upsert` function)

Perhaps event change the name to be FeedbackTable, QuestTable, etc, as per https://github.com/ExpeditionRPG/expedition-quest-creator/pull/210/files/ed45d0e79bd62b003904bee1b6091527d360e015#diff-b0299663938fc088f9f79f1748beaf22
- could then export it and reference it elsewhere

**Comment by smartin015** [comment]
We've since moved to sequelize.
