### ISSUE TITLE
Highlighting award-winning quests

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#232]
Ideas:
- Editor's choice (either as a separate table that would allow ordering, or a boolean column in quests table) <- this is how the Google Play market does it
- DB boolean column for award_winning, that'd show a little trophy icon next to it in search
- DB text column for award_won, could show a trophy icon in search listings and more info on the detail page ("Winner of Quest Quest 2")

Related thought for search, perhaps we should have quick-access tabs for common searches `Top Quests`, `New Releases`, `Family`, `Editor's Choice`?

**Comment by smartin015** [comment]
This all sounds good to me. What about quests with multiple awards?

**Comment by toddmedema** [comment]
Hmm. We'd have to do a quest_award join table with quest_id and award_id and the timestamp awarded, plus a table for awards (assuming, say, we awarded the same award to multiple quests, or at multiple times - such as "Quest of the Week").

That being said, a bit of a concern around highlighting awarded quests at the moment - the volume of quests is still low enough that the quests getting awards now aren't always superb (especially compared to, say, the quality of quests in 2-3 months once we have people motivated by money). So maybe editor's choice is a better starting point.

Or, we punt on this for a few months and instead start by / focus on exposing ratings + familfyfriend in search and sort. That feels like the right approach to me .... #RubberDucking

Additional inspiration from Amazon's book search:
- customer favorites
- "100 books to read"
- award winners
- start a new series
- book club picks
- shop by category

**Comment by smartin015** [comment]
I vote we punt for now.

**Comment by toddmedema** [comment]
Agreed
