### ISSUE TITLE
Add party information to ops context

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#24]
MVP: add access to settings.numPlayers and settings.difficulty

One of the unique aspects of roleplaying games is that your options are based on your character, ie if you're a mage, you can try to burn the bridge down; if you're a warrior, you can try to smash it.

Expedition quests aren't currently party-aware, which means our creators can't add these types of options to their stories.

Also, quests aren't aware of party size, ie you might have certain options (like sneak past the guards) if you're a small party, or "make a human ladder" if you're a large party.

Proposal:
- within `ops`, ability to access party info, such as `{{party.has.magic}}` or `{{!party.has.magic}}`
  - also have `party.size` (might also be worth allowing access to specifically alive and dead counts). 
  - should quests be able to change these variables? I can see changing .has.magic being handy, ie if the reward for a quest is learning a magic ability. `Party.size` could be useful if you earn a henchman, for example
  - for future combat hooks, getting number alive / dead would also be handy.
- the quest IDE (or app) automatically detects these and sets a metadata flag
  - if the quest contains at least one such check, the app, at the start of the quest (after choosing adventurers) to select which ability classes the party has
    - proposal: this selection list should look like existing choice nodes, but with a large and obvious checkbox on the left side. The "next" node on the bottom should indicate how many are selected (ie `Next (3)`), and should be disabled until at least one ability class is selected
- the IDE also validates that all decision trees are possible; ie have at least one option that doesn't require a skill set, or has options that span all possible skillsets (which might be hard to check for?)
  - this should be part of the DFS idea we're playing around with here https://github.com/Fabricate-IO/expedition-quest-creator/issues/68

**Comment by smartin015** [comment]
We now have number of players accessible in ops. Difficulty would muddy things around what the difficulty setting actually means (currently it's a strong mapping to combat difficulty).
