### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#255]
To help people better keep track of their ideas, we should allow for notetaking in a separate panel than the app. Some additional parsing could be done on the note text to inline help tooltips, spellcheck, and/or text completion. E.g for something like this:

```
Baron Badass: The protagonist of the quest. Enjoys cheese and kicking butt.
```

We could text-complete and spellcheck occurrences of `Baron Badass` in the quest, and set hovertext to the first bit of text.

Clicking defined words in the IDE could open the notes panel, and clicking it in the notes panel could step through instances of the word's use.

**Comment by toddmedema** [comment]
Also thought: if you mention an ID in the notes, would be cool to make it a link to scroll the editor to that ID, a la https://github.com/ExpeditionRPG/expedition-quest-creator/issues/72

**Comment by toddmedema** [comment]
As discussed, trimming down the spec on this issue to just be notes / no fancy dictionary or ID linking. We can always roll those out later, but no point in holding up an already-useful feature :)

**Comment by smartin015** [comment]
Closing for now since the main feature is complete.
