### ISSUE TITLE
_. function for singular vs plural adventurers

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#257]
I think it'd be useful to have a function like `{{_.soloOrParty(string1, string2)}}` that serves as a shortcut for writers to say things differently depending on if you're playing with 1, or multiple, adventurers.

For example: "She hands each of you" vs "She hands you"

You could theoretically do something like that with multiple and-checks, but that'd be messy and time consuming to type out every time.

Questions:
- Does that make sense as something we should add to / support in the API?
- What should it's functionality be / what should we call it? For example, should it be a single function that decides between two options? Should it be two separate functions, i.e. `ifSolo` `ifParty` that return the provided string or a blank string?

**Comment by smartin015** [comment]
Backlogging for now

**Comment by toddmedema** [comment]
This is already fairly straightforward with _numAdventurers, and generally best to keep the API small, so removing this from backlog
