### ISSUE TITLE
Use an ORM lib for data storage + separate dev from prod

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#258]
*Migrated to expeditionrpg/expedition#296 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

If we use [sequelize](http://docs.sequelizejs.com/en/v3/) or something similar, we won't have to worry as hard about what data storage mechanism we use, and we'd actually be able to unit test things (since postgres doesn't allow ephemeral inmemory tables).

**Comment by toddmedema** [comment]
Not pressing, but will make SQL testing easier - https://github.com/ExpeditionRPG/expedition-quest-creator/issues/184

**Comment by toddmedema** [comment]
Once we do this, we can also block localhost from accessing prod
