### ISSUE TITLE
Make app settings configurable

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#261]
*Migrated to expeditionrpg/expedition#298 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

In QuestAppBarContainer, `playFromCursor`

**Comment by smartin015** [comment]
Backlogging.

**Comment by toddmedema** [comment]
Removing from backlog; having contentSets be properly populated is pretty important, and while we're in there, we might as well at least set player count to be the minimum number required by the quest

**Comment by toddmedema** [comment]
Note that as part of https://github.com/ExpeditionRPG/expedition-quest-creator/pull/447, this now uses quest settings for min players and if horror is enabled, but would still be nice to have other customization options.
