### ISSUE TITLE
Refactor: Split out Quest Creator front-end from Expedition API, add serverside typescript + Hapi

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#266]
Allows QC to be hosted on CDN, will make it easier to convert the API part to typescript

Will have to host them in two separate places (api.expeditiongame.com?) - will need to leave quest creator running API as well for a while, to support older versions of the app / that don't point to the new URL

Big things to do post-refactor:
- Fix QC error definition generation + testing: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/271
- API-based announcement bar for app + QC: https://github.com/ExpeditionRPG/expedition-app/issues/370
- Make sure we're doing a good job of handling 500 errors and try/catching problems: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/186
- Make sure we're doing a good job of at least not breaking on non-latin1 characters (unit tests!!!) https://github.com/ExpeditionRPG/expedition-quest-creator/issues/157

**Comment by smartin015** [comment]
I took a quick exploratory crack at getting the server running typescript. To use webpack to compile backend typescript, we can't use webpack-dev-server on the backend to host HMR files for development. The whole thing gets way simpler if the QC frontend is separate from the API server.

**Comment by toddmedema** [comment]
Sounds about right. So, perhaps tomorrow morning we can set up that redirect so that we can do the separation in a month or so :-)

**Comment by smartin015** [comment]
We're coming up against more and more things that are predicated on splitting this out.

**Comment by smartin015** [comment]
We should use typescript server-side --^
