### ISSUE TITLE
New button no longer creates new quest

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#269]
Redirects to homepage, which /used to/ create a new quest automatically

**Comment by smartin015** [comment]
Backlogging for now (higher priority stuff happening)

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-quest-creator/commit/09e45c2ccf4f3dbaf6fd7d2287d059467180edaf
