### ISSUE TITLE
Far-future idea dump

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#27]
*Migrated to expeditionrpg/expedition#269 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

- node view
  - ability to see diffs of nodes, esp before publishing / vs currently published version
- Default choice option. IE if you have one (or more) choices with conditions, would be nice to define the final choice as the "if no other choices on this card trigger, show this one"
- Throw error if user tries to start a quest with combat - must give players some sense of who they are and where they are!

Macros, loading themes and expansions:

```
{{food = check if they have enough food, if not, goto; food-=1 }}
**macro food** or **function food**
**load cards pirates**
**unload cards pirates**
**theme pirates**
```

- Typecheck ops variables, ie if you set dayCount to a number first, it'd likely mess up parts of your quest logic if it later gets set to a boolean (ie it could go from displaying a number to users to conditionally hiding text...)
- use DFS to check for highly cyclical quests, ie where (say, for 4 or more) decisions, there's a consistent 1 or consistent 2 RP card gap, which might result in the same player making the choices

**Comment by smartin015** [comment]
Backlogging.
