### ISSUE TITLE
Improved `alert()`

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#273]
Create a new dialog showAlert function that takes in just a title string, alert string, and optional error string. It then shows it in a formatted / thematic alert window that is just as easy to use as window.alert, but adds in handy boilerplate like "If this issue persists, please email support" with action buttons "ok" and "contact support" (which auto-populates with browser and error information)

**Comment by smartin015** [comment]
Done.
