### ISSUE TITLE
First-open tutorial

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#276]
Walk the user through the basics.

Perhaps using http://introjs.com/?

Very well-supported library that supports both highlighting / pointing to specific elements, and center-of-page instructions (in the same flow, even!)

**Comment by toddmedema** [comment]
Closing for now; current "intro quest" does a decent job. Even if this was an improvement, it'd be one more thing to maintain / get out of sync with new features

**Comment by smartin015** [comment]
Intro quest has sufficed, this isn't needed.
