### ISSUE TITLE
Series / seriesnum

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#283]
@smartin015 Idea: To make it easier for writers to create multi-part series, I propose two new quest fields based on an idea I saw in the Kindle Author's Central: series name, and the number in the series.

Series name would autocomplete from all series the current author has published so far. It could /potentially/ be stored as a numeric ID that maps to series name + quest author, so that multiple authors could publish series' of the same name... or, we could just enforce unique author id + series name text inside of the quests table.

Once we have these as metadata, we can remove them from the title (making titles shorter), provide recommendation at the end of a series quest (ie "start part 2 now!"), and maybe even start to display series in a different manner in search results (for example, if you wanted to go on a quest that was at least 4 hours, it could be smart enough to aggregate total length of series).

The only concern I can think of with this implementation is that it removes the possibility for branching series, ie if you kill the king go to quest 2a, if you don't, go to quest 2b. That being said, that sort of branching could turn out to be a real headache - you'd have to do a really good job of saving state across quests, and it'd totally break if, say, you tried to play Expedition on someone else's phone (a pretty reasonable use case to expect).

Thoughts?

**Comment by smartin015** [comment]
Keeping state across quests would be a mess anyways, since it'd be very hard to verify automatically that the right state exists from the old quest into the new. We can roll with this idea for now, as I don't think it necessarily prevents us from adding branches (would just be additional quest metadata that says "don't treat this as a series").

**Comment by smartin015** [comment]
Regardless of effort, backlogging for now.

**Comment by toddmedema** [comment]
Closing, duplicate of https://github.com/ExpeditionRPG/expedition-api/issues/16
