### ISSUE TITLE
Published quests validation script

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#286]
*Migrated to expeditionrpg/expedition#302 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We could develop a simple web service that periodically crawls though **all** published quests using the new crawler code.

This lets us:
- Check for regressions in the app's ability to parse published quests when we roll out a new version
- Find and unpublish quests published several versions ago, so that users don't come across weird issues from less polished versions of the creator/compiler
- Update quest metadata (such as the play time estimates) across all quests when we update whatever process we use to generate that metadata.

MVP for this would be a simple node script that, when run, crawls all public and logs the broken ones to the console.

**Comment by toddmedema** [comment]
I dig the MVP script - automation (especially with the power to unpublish / manipulate prod) is a bit scary, but this'd be very handy even just as an internal tool to both test / refine the crawler, and to do analysis on published quests.

"Find and unpublish quests published several versions ago" <- would it be worth publishing the current quest creator version as part of quest publish metadata? Might be a lifesaver for migration / bugfixes...

**Comment by smartin015** [comment]
Yes. A thousand times yes. We should absolutely include the version as part of the metadata, because then we have even more information on which version of "older compiler version" quests fail due to new stuff.

And yeah, maybe we can dry-run the automation at first and take manual action on what it discovers. If the volume ever becomes too much, we can always switch it on auto :)

**Comment by toddmedema** [comment]
Split version tracking to new issue: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/289

**Comment by toddmedema** [comment]
Too much effort for reward right now

**Comment by toddmedema** [comment]
Idea from IRL: adding this to unit testing (or maybe just CI); then also lets you get a report along the lines of "your changes would break these quests in prod:..."
