### ISSUE TITLE
Support for tri-state buttons

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#287]
i.e. buttons could be "disabled", "enabled", or "visited".

**Comment by toddmedema** [comment]
I could see this either as a simple flag (ie if the node this button points to has been visited before... wouldn't that require that that node have an ID to keep track of it?)

and / or, give quest creators the ability to edit this state by supplying a conditional, ie `{disabled: gold < 10}` - which could be a way to hint at players about other options that are present but not unlocked (yet). However, I think that would be most useful as a separate, "disabled" state... and then buttons start to get confusing

**Comment by toddmedema** [comment]
Moving to backlog, lots of other big fish to fry first
