### ISSUE TITLE
Pay what you want: Stripe integration

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#298]
Stripe: https://stripe.com/docs/charges
- [x] don't need a token endpoint on our server, just a charge endpoint
- [x] /stripe/charge: create a charge and pass results back to app; add a metadata object to charge to include relevant info
- [ ] Set up Author authorization / account creation: https://stripe.com/docs/connect/express-accounts
  - [ ] `Authors` table. For now just google id, email and stripe id
    - [ ] Fetch + attach author info to quest.publisher (not quest.author, b/c already used...) on quest details fetch
      - [ ] Quest migration plan, ie what do we do with quests created pre-author table? Ideally switch to paying to Expedition directly / still allow PWYW. Also, after prod QC deploy, we can migrate the app to use quest.author as an object, but copy it from quest.publisher if that's being sent from the QC (then, in a month, have QC return as quest.author and remove that patch from app)
    - [ ] Using Express account type option, send destination account and amount: https://stripe.com/docs/connect/destination-charges
- [x] make sure API errors are getting handled properly, ie send a non-200 response back to app if something's wrong
- [ ] Final test w/ app + QC: https://github.com/ExpeditionRPG/expedition-app/issues/362
  - [ ] Can tip on a non-enabled quest; message changes to "Pay What You Want"
  - [ ] Can enable a quest to receive tips / register an author 
  - [ ] Can tip a quest, and that tip goes to the author w/ us taking a 10% cut

Future:
- [ ] Save payment: https://stripe.com/docs/sources/customers
  - [ ] First, figure out what the UI needs to let users select their payment source...
    - [ ] We'll probably need to send the UI the DB user object (incl stripeId) not just the Google Auth results
  - [ ] Create `user` db entry on login if it doesn't exist, or update lastLogin if it does
  - [ ] On charge, if !user.stripeId, call customers.create w/user.id and set it to the returned id if that succeeds, and THEN create the charge
  - [ ] Send user.stripeId with charges if it exists
  - [ ] Attach usage = reusable source to customers
- [ ] Switch from Express to Custom writer signup flow for more countries + more control (but more engineering effort)
- [ ] Recurring monthly user payments (Expedition Adventurer's Club)
- [ ] Support to split tips across multiple co-authors

Notes from previous integration attempt:

We'll need to get writers set up with sub-merchant accounts if they want to accept tips. For any quest whose author doesn't accept tips (either because they haven't set it up, their account is still pending, or live outside of the US), we should change the prompt in the app to be "Support Expedition" and have the payment go to our master merchant ID.

Braintree sandbox login page: https://sandbox.braintreegateway.com/login

We'll need:
- `author` table matching their google account info to merchant info they enter and their resulting submerchant id and merchant status.
  - TODO: figure out what the primary key for this should be. Probably email address, since I don't know if the Google auth id is everlasting. Some Google logins don't include user.email, though? So we might have to prompt those users to enter their email... but then how will we know it's them in the future? Do we accidentally have Google Auth.email set as optional instead of required?
- An author profile dialog (accessible by clicking on their profile image in the top right -> Profile) that prompts them for the details required here: https://developers.braintreepayments.com/guides/braintree-marketplace/onboarding/node
  - It looks like SSN is optional and you can use email / phone as funding to send funds via Venmo, so that we don't have to deal with sensitive SSN and bank details. Seems like a worthy sacrifice for an MVP
  - When they update their profile, have the option to submit to become eligible for tipping. At that point, we'll fire off a call to Braintree that'll return their merchant id and status = 'pending', which we should save to their profile: https://developers.braintreepayments.com/guides/braintree-marketplace/confirmation/node
  - We then set up a webhook that will listen for Braintree either confirming their account or declining it - https://developers.braintreepayments.com/guides/braintree-marketplace/confirmation/node
    - Question: will they also email us if it's declined, or should we have that webhook email us?
- terms of service! We'll likely need general player TOS now, and will need to tack on Braintree's to ours - https://developers.braintreepayments.com/guides/braintree-marketplace/onboarding/node
  - link to this on the main website, quest creator, and app store listings
#

**Comment by toddmedema** [comment]
Alternatively, an easier MVP solution (and possibly as good or even better from a business / marketing perspective) would be to make tips invite-only and set them up by hand.

Will still need author table to store the merchant id, but then don't need to worry about storing address and other PII

**Comment by toddmedema** [comment]
Backlogging until October / expansion things are done

**Comment by smartin015** [comment]
This is done.
