### ISSUE TITLE
Performance issue with crawler

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#319]
Currently disabled on prod (`dispatch({type: 'QUEST_PLAYTEST', msgs: playtestXMLResult(questNode)});` is commented out in actions/Editor)

If you try it on a long quest like ID 0B7ligyKcIb7OWUhPQ0dNemZUUkE by hitting "Play from Cursor", it'll max out CPU and suck up 3GB of RAM, then crash the process.

Admittedly, that quest does have a lot of loops (It's the green rats one, so you're exploring districts, and then going back and choosing another district... there's even a choice at the end of the game to replay it from the start, along the opposite branch).

But, that's also exactly the sort of quest where this is useful. If there are no branches, then there'd be no crawling errors to catch :)

**Comment by toddmedema** [comment]
Following up here - apparently a quest I wrote almost a year ago has been broken the entire time b/c it was referencing ID's that didn't exist (in some branches). I wonder how many people had a bad experience because of that.... needless to say, would be good to get this fixed to prevent that in the future!

**Comment by smartin015** [comment]
Performance (or at least breadth of search) should be greatly improved by https://github.com/ExpeditionRPG/expedition-qdl/pull/7
