### ISSUE TITLE
Proposal: programmatic macros

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#322]
To allow better support for detecting if a quest uses the expansion or not (and allowing future programmatic versions of the game via the service that keep track of health, auto-handle rolls, etc), I propose:

`{{heal(1)}}`
`{{health(-1)}}` (redundant with heal, but clearer in the negative case)
`{{persona(1)}}`
`{{drawLoot([1, 0, 2]}}` (aka draw 1 tier 1 loot, 0 tier 2, 2 tier 3)
and some way of programmatic roll choices

Technically, the only one required for expansion detection would be persona, but I think it'd be easier to implement and train new users on all of them at the same time.

Thoughts @smartin015 ?

**Comment by toddmedema** [comment]
(For things like `{{heal(1)}}`, the app would then transform this into stock text saying "All adventurers gain 1 health")

**Comment by smartin015** [comment]
IMO this adds extra mental overhead ("was it `loot`? `drawloot`? `drawLoot`?") and may give us a false sense of security in assuming that people actually use these methods. Why not just have a switch button on the publish page that enables/disables a requirement of the new expansion? We should be able to catch miscategorized quests when we audit them as they're published.

**Comment by toddmedema** [comment]
Perhaps - but that's only half the problem. The other half is that Expedition as a service doesn't really work / make sense without these. Ie if a quest says "Reduce health by 1", that only makes sense if you have cards / would never work as a chatbot, web-only version, voice assistant-only version, etc.

Possibilities that might help:
- create two or three variants for each (ie health / heal, loot / drawLoot)
- have the crawler throw an error if it's an unrecognized command, and perhaps suggest the nearest-spelling command like spellcheck (ie `drawloot invalid. Did you mean drawLoot?`)
- have the crawler check for and give warnings for regex phrases like "heal X" or "draw loot", and suggest that writers use the functions instead. We won't have perfectly migrated / programmatic quests now, but if we don't start sometime, we never will :)

**Comment by toddmedema** [comment]
Rendered obsolete by better implementation idea: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/341
