### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#327]
Having consistent styling for things will make future migrations / improvements / experiences easier to implement, as well as keep common idioms easier to understand for players and new writers.

Some ones I've noticed, @smartin015 LMK if there's anything you'd want to add / change. Thinking this could be a new top-level doc - https://github.com/ExpeditionRPG/expedition-quest-creator/blob/master/docs/index.md

## Titles

Quest Titles Should be Capitalized, Just Like Books!

## Conversations

Follow book-writing best practices:
- Use double quotation marks, separating speakers with new paragraphs and a new set of quotes.
- Long speeches from a single character may be broken into multiple paragraphs. Each new paragraph should start with a quote, but only the final paragraph should close with a quote.
- Since players will be reading the dialog out loud, avoid having single paragraphs more than 4 or 5 sentences in length. Also try to keep individual pages to the size of the screen (around 4-8 sentences; you can check this in the Quest Creator by hitting "Play from Cursor") so that one person isn't stuck reading the whole story.
- Punctuation marks should be inside of the quotes
- Capitalize the quoted speech
- Indicate who is speaking (not always necessary if there are only two parties speaking, but can still reduce reader confusion)
- Intermix dialog with action
- Active / now tense and second person is best since players are reading as it happens. For example: `The guard asks you, "Where do you think you're going?". How do you respond?`, not `The guard asked them, "Where do you think you're going?". How did they respond?`.

A full dialog example:
```
The priest begins, "This is a really long story.

"A story so long, in fact, that it spans multiple paragraphs!"

The warrior yawns in boredom. 

"Hand me that screwdriver," the mechanic grins, wiping her grease-covered hands on her jeans, "I bet I can fix this thing."

* Hand her the screwdriver

  Something 

* Chastise the warrior for yawning

  Something else 

* Listen to the priest
 
  Something new
```

More good examples and resources: [one](http://www.writersdigest.com/editor-blogs/there-are-no-rules/keep-it-simple-keys-to-realistic-dialogue-part-i), [two](http://www.wikihow.com/Format-Dialogue-in-a-Story)

## Combat

Would be good to specify standard balance. Both standard tier progression and, if you want to veer from that, how you'd need to otherwise equip players for harder battles (ie normally ~3-4-5-6, but for each two tier of loot provided, you can make one battle one tier harder)

Once it's ready, we can also include standard examples for `on round` and `on surge`

## Instructions

Generally, try to organize instructions with the most important information first, and have all closely related instructions in the same block. For example:
```
> Svella casts Fireball. Roll once. If [roll] > 10, deal one enemy 3 damage.
> {{prepared==true}} +2 to Svella's roll.
> Draw one tier II loot.
```

## Skill checks

Skill checks should generally result in branches of similar lengths - otherwise, you end up with quests that have hugely variable lengths depending on how lucky you are. A couple of examples on how this can work:
- If you're sneaking past a guard and you succeed, perhaps you only fight one guard instead of many, so that you always do combat.
- If your adventurers choose a pacifist path, instead of encountering combat, give them a puzzle to solve or an equivalent amount of roleplaying / storytelling (for reference, each combat generally lasts around 5-10 minutes, or 5-10 roleplaying cards)
- If you're doing a perception check and succeed, you might see additional details, perhaps even a new room to search. If you fail a perception check, perhaps you think you see something and investigate it closer, only to find out it was a shadow / rock / tree / etc.
```
> Roll to sneak past the guard.
* [roll] ≥ 15
  Something happens
* [roll] 10 - 14
  Something else
* [roll] < 10
  Something new
```

## Drawing loot

Note that the number of loot to draw should be the word, tier and loot are not capitalized, and the tier number is written as a Roman numeral.
```
> Draw one tier III loot
```
- Generally try to avoid "Each adventurer draw one loot" as this imbalances the game and makes larger parties overpowered.

**Comment by smartin015** [comment]
We could relax the rules for paragraph length for single-player-only quests.

Otherwise, SGTM.
