### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#337]
Since we have significant reach into custom user content, we should provide a ToS that lists the terms the user is agreeing to.

**Comment by toddmedema** [comment]
Backlogging till main expansion things are done. Important legally.... but a lot of work, and few people /actually/ cares about ToS / doesn't really make the game better

**Comment by toddmedema** [comment]
Some initial work / ideas here as part of looking into contractor contracts: https://docs.google.com/document/d/1LYaDX6h9fDU9T9IxrcWeOKtZ4xxc0xI663dKnLRiYl8/edit
