### ISSUE TITLE
Writing bug we should catch: misspelled enemies

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#353]
For example, Theif instead of Thief. Basically, should show an error that says "Enemy not found; please check your spelling. If you meant to create a custom enemy, make sure to define its tier and health!"
>> Related, don't know if quest creators currently have the ability to show health for custom enemies, but that's an absolute requirement for them to work...

**Comment by smartin015** [comment]
Done with the crawler.

![nonstandard_enemy](https://user-images.githubusercontent.com/607666/30250654-54ec6546-9620-11e7-83b3-6ccd7f4ce158.png)
