### ISSUE TITLE
Brainstorming: how do we get more people writing quests?

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#37]
@smartin015 please add your thoughts when you have a chance :) If we can't figure this one out, it's all for moot:

0. perhaps people will be more excited to write quests with game in hand, but we /really/ don't want to wait until then for people to start writing, otherwise we'll have thousands of people playing but still only have two quests available....
1. marketing? Unsure what we'd pitch as to why they should write a quest, though. Seems like we should figure out incentives (see 3) before spending money on marketing
  i. every time we post a mailing list or Kickstarter update with new features, we get a significant number of visits to the site, but nobody actually writing anything. Perhaps it's related to number 2, that people are excited, but still confused on how to use it?
2. maybe people are getting lost / confused. Could have the front page give a better explanation + get people pumped, before dropping them cold-turkey into a text editor. And perhaps there are still things about the editor itself that are confusing. It's certainly intimidating as a text editor
3. incentives? Offer $25/ea for the first 5 completed quests? But how do we incentivize people to write quality quests, not just lots of quests
  i. we'd talked about creating a quest marketplace where creators could charge for their quests / get paid for writing them. Coding for purchases would obviously be a big pain, but I wonder if we could solve half the problem by putting up money, ie saying that for each unique user that plays through their quest, we'll pay them (50 cents? a dollar?)

**Comment by toddmedema** [comment]
From in person, experiments we'll be trying first:
- doing what we can to make the editor more user friendly to address (2) (insert drop down, syntax that's easier to remember / less JSON dependent)
- running a quest writing contest to address (3)

Once both experiments have been live for a few weeks, we should revisit to see how successful they've been / what our next batch of experiments should be

**Comment by smartin015** [comment]
Closing as obsolete
