### ISSUE TITLE
Crawler freezing page / poor UX

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#379]
Try it on: https://quests.expeditiongame.com/#0B7K9abSH1xEOV3M2bTVMdWc4NVk

Any time you make a change and try to playtest it, the entire page freezes up for several seconds - which is annoying because you're actively trying to do something (playtest). We should either figure out a way to make it not freeze the UI (such as setTimeouts every ~100ms), or queue it to run the crawler on change, and then run it after there's been no interaction for a few seconds - and / or, display in the UI when the crawler is running, such as turning the "view errors" button into some sort of "checking for errors" spinner.

Also, it erases crawler errors as soon as you type something (spellcheck), so perhaps we should just disable it for now since that's a lot to fix?

**Comment by toddmedema** [comment]
Apparently Google actually recommends having individual timer tasks take 50ms or less for the best experience

**Comment by smartin015** [comment]
I get "file not found" when I attempt to try the link (it's probably not shared with me).

The crawler shouldn't even be causing UI issues; it's run in a separate worker.  Do you know where the slowdown is occuring?

**Comment by toddmedema** [comment]
Weird, it's definitely shared with you. It's "Test Quest" in drive/expedition/quests, so you can try opening it from there. It appears to be happening on almost every quest I open. 

Note that as a quick fix, I went ahead and removed playtest.js from prod because I remember you saying that it gracefully degraded (confirmed it's still working). We'll have to debug locally.

Looking at the test quest locally:

- It maxes out the CPU entirely for 10 seconds; even if it's supposed to not interfere with the UI, it's using up all of the resources, and should probably incorporate some pauses / setTimeouts to mitigate if we're going to run it in the background (or, if it really is this CPU intensive, maybe we stop trying to constantly run it, and move it to a separate "Playtest / Validate" button with a progress indicator?)
- It also seems to not know when to stop: This quest is only 100 lines, and yet it logs : 34692x `... (queueLen: 13 NaN)`. There is a circular loop in it, but I bet there's at least one circular loop in every quest / I thought there was a MAX_LENGTH safeguard against that.

**Comment by toddmedema** [comment]
Random idea for handling the playtest errors disappearing after the next spellcheck: we could potentially store two different arrays of logs / errors (spellcheck and playtest), and have a merge function that displays both of them. Would also prevent playtests from erasing spellcheck errors, and would allow us to add other asynchronous sources of errors (for example, a fast playtester and a slow playtester, or an external web service that checks grammar)

**Comment by toddmedema** [comment]
Note: would love to see this fixed; someone just published a quest with GOTOs pointing to IDs that don't exist :)

**Comment by smartin015** [comment]
Now that https://github.com/ExpeditionRPG/expedition-app/pull/482/files is published, we need to detect GOTOs from a single combat interstitial to another combat interstitial and error on it.
