### ISSUE TITLE
CRON email(s)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#394]
*Migrated to expeditionrpg/expedition#313 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

A couple of possibilities for ways we could keep authors engaged:
- surveys after certain experiences (ie just published your first quest, what can we do to make your publishing experience better?)
- inactive accounts (ie lastLogin > 1 month ago, we miss you!)
- authors who published part of a series > 1 month ago, how's the next part going?

Note that it might be wise for us to add an unsubscribe option to QC emails soon (separate from Mailchimp email list) before we get flagged for spam. We'll also want to be extra careful about keeping track of when these fire / not firing them multiple times to respect authors.

**Comment by 7thSentinel** [comment]
I like the survey idea.  

I've only gotten one response back so far after reaching out to authors who have quests not publicly published.  

He thanked me for the e-mail but said he was busy with other projects at the moment. 

Might try reaching out to him again after the New Year comes.
