### ISSUE TITLE
_.isSurgeRound() not working

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#397]
Hello,

I was trying to use 
`* {{_.isSurgeRound()}} on round`

which is actually not working. I then went to the code of the app, and the correct syntax is:

`* {{_.isCombatSurgeRound()}} on round`

could you correct that in the MD file?

**Comment by smartin015** [comment]
Thanks for bringing this to our attention, Arcanalreanol :) I've updated the docs to fix it.
