### ISSUE TITLE
too dark Icon color during combat

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#399]
whenever we use an icon into a round, the icon's color is too dark to be seen properly

here is a sample:

```
* {{ malus }} on round
 
  > :roll: You are drunk, -1 to all your roll during this combat```

**Comment by toddmedema** [comment]
Hey @ArcanaIreanol thanks for reporting this! I've moved this to the app's repo, which is where the root of the problem is: https://github.com/ExpeditionRPG/expedition-app/issues/484

(Feel free to subscribe there if you'd like to stay up to date)
