### ISSUE TITLE
Italic tag closed but not working properly

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#400]
Into a same paragraphe, I used the `<i>` tag twice to do some text formating. unfortunately, even though the tag is closed, the rest of the text is still italic

FYI: if there is only one `<i>` tag, it's working normally

here is my buggy code:
```
You're now entering the <i>Dead Flying Drinking Crow Skull</i>,
city of <i>New-Terbeeble.</i>

By the way, you really think the tavern's name is too long. 
```

here is how it's rendered:

>  You're now entering the _Dead Flying Drinking Crow Skull, city of New-Terbeeble._
>  
>  By the way, you really think the tavern's name is too long.

You can clearly see that ",city of" is italic, even though it shouldn't

**Comment by toddmedema** [comment]
@ArcanaIreanol thanks for reporting this! Definitely a bug. Fixed here: https://github.com/ExpeditionRPG/expedition-qdl/commit/bb72ff11a409776496637a1fbed82ddf26f524fd

Should get deployed later today :) (Note that this bug affects the published quest output, so if you published a quest while it was present, you'll need to update /re-publish it to fix it)
