### ISSUE TITLE
Crawler: Automatically generate min & max duration

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#409]
Rather than have writers attempt to guess how long their quests will take to play, we could use the crawler to calculate a rough (good enough) estimate, as well as score their quest on replayability. Then show those #'s in the publishing dialog as disabled inputs, and provide some help / hover text about what goes into each of them.

Thinking min and max length could look at shortest and longest paths (have to be careful about puzzles with loops for max paths), and score them based on number of cards traversed, maybe 1 minute per roleplay and 8 minutes per combat.

**Comment by ArcanaIreanol** [comment]
Could also be nice to "adapt" based on statistics ;-)

**Comment by toddmedema** [comment]
Split out replayability score to a separate issue, backlogging for now https://github.com/ExpeditionRPG/expedition-quest-creator/issues/424

**Comment by toddmedema** [comment]
Shower thought: Would be good to provide a min + max amount for each part of the crawl; for example, combat "takes 5-10 minutes" is a more useful estimate than "all combat takes 5 minutes". In fact, we could improve the min-max estimates in a few more ways:

- Combat duration is based on both the tier and number of players; I would say that a decent estimate might be `combatMin = (1 + tier * 1.5) / (Math.log(quest.minPlayers + 1))` and  `combatMax = (2 + tier * 2.5) / (Math.log(quest.maxPlayers + 1))`
- Roleplaying cards might have a "slow" and "fast" read speed
- Perhaps only increment max playtime on loops back to the same node (for example, in a puzzle, the min playtime would be if they solve it on the first go, the max playtime would be if they brute force guess it)
- Only stop playtesting once the min playtime is > 2 hours (or other things, like depth / timeout stop it)

**Comment by toddmedema** [comment]
Closing, turns out this is NP hard and not possible to implement.
