### ISSUE TITLE
Request: Empty action goes to goto automatically

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#412]
*Migrated to expeditionrpg/expedition#316 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Sometimes, I'd have loved to have in my quest a moment when there are 3 choices, that sets different stuff in variables but only goes to one place after that.

Problem: when, after a choice, there is content consisting of variables sets, it creates an empty screen, with a next button.
It would be awesome to automatically go to next in that case. cause it's bad for user experience though it allows programmer to create more complex stuff

example:

```
_Test_

lorem ipsum dolor et sit amet

* choice 1

    {{variable = variable + 1}}

    **goto foo**

* choice 2

    {{variable = variable - 1}}

    **goto foo**

* choice 3

    **goto foo**
``` 

in this example, if you hit choice 1, you'll have an empty screen with a next button (to go to #foo). and the variable would be set to ++. same if choice2 (variable--).
and in choice 3 you'd directly go to #foo, without an empty screen in between (because there would be no need to update variable)

**Comment by toddmedema** [comment]
That seems pretty reasonable! @smartin015 can you think of any reasons not?

**Comment by danielwiktorczyk** [comment]
I was thinking of this too when writing my quest, would really like to see this be added!
