### ISSUE TITLE
Request: goto {{variable}}

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#417]
I want to implement some kind of a merchant shop that the party could check whenever they are in the city. The problem, is that I want that they can exit this merchant shop and go back to the previous screen.

for now my only possibility is to copy paste the merchant shop's code each and every time they could go to it, because we cannot set the last place they were to go back there directly

what I want:
```
_Streets_ (#street)

{{ gold = 35 }}
{{ lastId = "street" }}

:loot: Party's gold: {{gold}} :loot:

As you leave the tavern, you're now wandering in the streets of <i>New-Terbeeble</i>

* Visit the Merchant Shop
  ** goto shop **

* Continue quest
  ** goto street2 **

_Merchant Shop_ (#shop)

:loot: Party's gold: {{gold}} :loot:

Welcome to my shop, here you can buy very interesting items

> {{ gold < 10 }} You don't have enough money to buy anything

* {{ gold >= 10 }} :loot: Buy Tier I loot (10 gold)
 
  {{ gold = gold - 10}}
  
  > Draw one TIER I loot card
  
  ** goto shop **
  
* Exit
 
  ** goto {{lastId}} **

_Streets_ (#street2)

lorem ipsum
```
` ** goto {{lastId}} **` is not working in that case (runtime error: "Cannot read property '0' of null")

for now, my only solution is to copy this merchant code over and over and over again

**Comment by ArcanaIreanol** [comment]
another possible workaround for me would be to create every possible Exit button... but again, it's quite a lot instead of having the goto {{var}}

**Comment by toddmedema** [comment]
Perfect timing :) Scott just figured out a way to do this last night, we should have it deployed to the QC and App by this weekend - https://github.com/ExpeditionRPG/expedition-qdl/pull/26
