### ISSUE TITLE
Issue: can't use a variable in an action nor a choice

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#418]
I can use a variable to act as a condition, but I can't use the variable in the text of the button/action

following code does not show the button `Buy Tier I loot (10 gold)`
```
{{tier1Price = 10}} 

> {{ gold < tier1Price }} :loot: You don't have enough money to buy anything

* {{ gold >= tier1Price }} :loot: Buy Tier I loot ({{tier1Price}} gold)
    ** goto foo**
```

but this one does
```
{{tier1Price = 10}} 

> {{ gold < tier1Price }} :loot: You don't have enough money to buy anything

* {{ gold >= tier1Price }} :loot: Buy Tier I loot (10 gold)
    ** goto foo**
```

**Comment by toddmedema** [comment]
Interesting! Put in a PR to fix it here: https://github.com/ExpeditionRPG/expedition-qdl/pull/29

If it gets approved / doesn't run into any issues, should be rolled out within the next week :)

Thanks for pointing this out!

**Comment by ArcanaIreanol** [comment]
cool, thanks
