### ISSUE TITLE
NTH: select menu / dropdown list

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#420]
*Migrated to expeditionrpg/expedition#317 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Would ne really nice to be able to make a dropdownlist to assign it to a variable.

Usage would be mainly for gambling.

I have no clue how to implement such a feature :p

**Comment by toddmedema** [comment]
We've been kicking around ideas for new inputs! Drop downs and text inputs both seem like good candidates. Thinking it would work something like `{{ var = Dropdown(['option 1', 'option 2'])}}` or `{{var = TextInput()}}`

Think it would definitely open up new storytelling possibilities, but going to have to put it on the backlog for now, until we deliver on the current stretch goals!

Keep the ideas coming :)

**Comment by ArcanaIreanol** [comment]
Cool. Yeah, when I wrote this, I was like "could be nice, but I'll sure they have a zillion things to do before :p
Hence the Nice To Have

**Comment by danielwiktorczyk** [comment]
It would also be nice to have dropdown lists available in the Quest Editor when choosing objects . For example, when creating _combat_ encounters,  having a quick reference for enemies available as an info bubble / some sort of selection interface within the editor appear. Similarly, a dropdown selection for available :icons: . This would beat having to refer to the excel doc of enemies + info  / icons.

**Comment by toddmedema** [comment]
@danielwiktorczyk good idea! Added a (backlogged) issue here for autocomplete in the editor: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/441
