### ISSUE TITLE
Playtester not catching node null errors

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#428]
Logged in as Fabricate, try playing through https://quests.expeditiongame.com/#0B9dCBAac9SVVeDNwVUF1UVlIZ1E

If you try playing from ~line 167, you'll get `cannot read property getTag of null` when you try to hit next.

For one, it would be hugely helpful if we figured out a more human-friendly way to describe that error.

But, for two, it's really weird that the playtester isn't breaking on this. This means that authors can accidentally publish totally broken quests :(

For what it's worth, this specific error was caused by an incorrect number of indentations, which we should also catch and show to the user (since that's an incredibly specific and helpful error): https://github.com/ExpeditionRPG/expedition-quest-creator/issues/357

BUT, before we fix that, we should use this as an opportunity to figure out why the playtester isn't failing when it should be.

**Comment by smartin015** [comment]
Requires 2fac, but this might be fixed by the non-nullable typework I've been running. Can you try this again from head to see if the behavior has changed?

**Comment by toddmedema** [comment]
Yep, seems fixed now. Caught and informed the user of the issue (incorrect indentation)
