### ISSUE TITLE
Error 502 - Quest creator - **goto ** command 

### ISSUE THREAD

**Issue by Shinji170981** [ExpeditionRPG/expedition-quest-creator#429]
Hello,

i would like to report an error in the quest creator.
I get the error on the **goto ** command.
The command is located on the 3rd level

    * on lose
 
    **goto Faery**

      _The park_ (#Faery)

**Comment by toddmedema** [comment]
@Shinji170981 it looks like your issue should be fixed by correcting your indentation. `* on win` and `* on lose` contents should be indented, just like a `* choice`. And cards that occur after / outside of the combat should not receive the extra indent. Try:

```
* on lose

  **goto Faery**

_The park(#Faery)_
```

Let me know if that fixes it for you!

**Comment by Shinji170981** [comment]
Hello Todd, 

I got it to work yesterday. 
The quest is working now.

Hopefully I can create more. :-) 

P.S. If you intend to publish the game in multiple languages, I could offer my skills as a German native speaker and my previous experience as a translator.

I have translated videogames like "Fly for fun" in the past and "Forsaken World".

Kind regards 

Mathias Eck 
-- 
Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 27/10/2017, 04:43 Todd Medema <notifications@github.com> wrote:
@Shinji170981 it looks like your issue should be fixed by correcting your indentation. * on win and * on lose contents should be indented, just like a * choice. And cards that occur after / outside of the combat should not receive the extra indent. Try:
* on lose

  **goto Faery**

_The park(#Faery)_

Let me know if that fixes it for you!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ExpeditionRPG/expedition-quest-creator","title":"ExpeditionRPG/expedition-quest-creator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ExpeditionRPG/expedition-quest-creator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@toddmedema in #429: @Shinji170981 it looks like your issue should be fixed by correcting your indentation. `* on win` and `* on lose` contents should be indented, just like a `* choice`. And cards that occur after / outside of the combat should not receive the extra indent. Try:\r\n\r\n```\r\n* on lose\r\n\r\n  **goto Faery**\r\n\r\n_The park(#Faery)_\r\n```\r\n\r\nLet me know if that fixes it for you!"}],"action":{"name":"View Issue","url":"https://github.com/ExpeditionRPG/expedition-quest-creator/issues/429#issuecomment-339857199"}}}

**Comment by toddmedema** [comment]
Thank you! It might be a while before we have the technology to translate quests, but if you'd be interested in helping translate the cards to German, email me at Todd@Fabricate.io :)
