### ISSUE TITLE
Images are broken in icons.md

### ISSUE THREAD

**Issue by A-zu-ra** [ExpeditionRPG/expedition-quest-creator#433]
Images do not show up as intended in icons.md; clicking on the image resource results in "Not Found". Presumably this can be fixed by redirecting to the new expedition-art repo directories?

**Comment by toddmedema** [comment]
Hey @A-zu-ra ! Sorry about that - we've moved the icon documentation to here: https://github.com/ExpeditionRPG/expedition-art#icons

But it looks like I forgot to update the links in the Quest Creator documentation - that should all be updated now. Thank you for pointing that out :)

**Comment by 7thSentinel** [comment]
I had an icon continue to show as a broken image in the (guided) quest "Bacchanalian Revels". 

Specifically, the :song: and icon is broken.  Made sure the "s" was lowercase too, as I've found an uppercase first letter causes them to break.

**Comment by toddmedema** [comment]
@7thSentinel ah, that's because it's `:music:`- here's the full list of icons: https://github.com/expeditionrpg/expedition-art#icons

**Comment by 7thSentinel** [comment]
In the immortal words of Homer Simpson,  "D'oh"!

I always want to call the music ability type song...

Why can't I get that through my thick skull!?
