### ISSUE TITLE
Buggy quest, won't load, can't unpublish

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#434]
I created a first quest months ago. At a point, I guess I created a bug and the quest won't load anymore

I did duplicate my drive file, and deleted the old one, so I can continue on my quest.

the first one still won't load, but the second does without any issue

here is my problem: since I privately published the first one, and I can't load the screen anymore, I can't unpublish it. and now it's staying in my "private quests" with no way for me to remove this buggy one

buggy one: https://quests.expeditiongame.com/#0B7biUaE6422bUVotZVFsVGZ1X3M
duplicated-working one: https://quests.expeditiongame.com/#0B7biUaE6422bS0RJSUNjZjU3TDA

I even tried to fake the api call (from debugger) to unpublish the first from the second one, but it won't either

**Comment by ArcanaIreanol** [comment]
ok, seems like after all, a fiddler call fixed it

**Comment by toddmedema** [comment]
@ArcanaIreanol to clarify - if you deleted your old drive file, how do you know it still won't load? (Quest Creator should fail to load if the file doesn't exist)

**Comment by ArcanaIreanol** [comment]
FYI: I managed to fake a unpublish api call from fiddler, with the buggy ID. It gave me a HTTP200 (response body: "ok"), but my quest still shows up

**Comment by ArcanaIreanol** [comment]
Maybe, next to this problem, it would be nice, from the quest creator, to have somehow a list of quests, with their state and some actions like:
```
+-Title-------------+-State-------+------------------------Actions-+
| Quest ABC         | Published   | Unpublish / Duplicate / Delete |
| Once Uppon A Time | Unpublished |   Publish / Duplicate / Delete |
| Foo Bar           | Unpublished |   Publish / Duplicate / Delete |
+-------------------+-------------+--------------------------------+```

**Comment by toddmedema** [comment]
@ArcanaIreanol gotcha. As a temporary solution, I've deleted the buggy quest from your private quest list. We've been discussing a quest management API like you suggest, but it'll be a while before we're able to get to it. As always, thank you for the feedback!
