### ISSUE TITLE
qdl_guide.md Document Issue

### ISSUE THREAD

**Issue by mlan225** [ExpeditionRPG/expedition-quest-creator#440]
DateTime found: 11/08/2017

## Context
The qdl style guide has different directions on creating card titles with IDs than the code accepts. 

Acording to the documentation within the qdl style guide, card titles with IDs attached to them are supposed to follow this syntax: _roleplay title (#here)_ , which causes an error in the IDE.

## Impact

Anyone looking at the docs for help on creating card titles with IDs and using pointers to navigate to them will encounter this issue.

## Expected Behavior

Following this syntax, the user is supposed to be able to use the pointer **goto here** in able to point to the card with the title and ID of _roleplay title (#here)_ 

## Actual Behavior

Following the syntax stated in the qdl style guide, when the user uses the pointer, **goto here**, in able to send the code to the card with the title and ID of _roleplay title (#here)_  , an error occurs in the IDE. 

## Steps to reproduce. 

1. In the quest creator, create a pointer with the id of 'here':
--> **goto here**

2. Create a title card with any title and the ID 'here' following the syntax in the qld style guide:
--> _title card (#here)_

3. Run the code and test the pointer to reach the error.
--> "Error! Uncaught TypeError: Cannot read property 'authorize' of undefined" 

## Screenshots / Screen captures

![screen shot 2017-11-08 at 9 24 36 am](https://user-images.githubusercontent.com/17088502/32555963-1e204828-c46c-11e7-9311-5b55ab1ca7f9.png)

![screen shot 2017-11-08 at 9 25 26 am](https://user-images.githubusercontent.com/17088502/32555977-26c3c310-c46c-11e7-82e9-23938f66c983.png)

![screen shot 2017-11-08 at 9 20 05 am](https://user-images.githubusercontent.com/17088502/32555990-2b3dbcb6-c46c-11e7-895a-1f87cd875cf5.png)

![screen shot 2017-11-08 at 9 54 31 am](https://user-images.githubusercontent.com/17088502/32556406-56f63d00-c46d-11e7-83de-be1152211b9d.png)

## Relevant URLs
- https://github.com/ExpeditionRPG/expedition-quest-creator/blob/master/docs/qdl_guide.md#pointers

##Other Information
- I believe now that the error thrown with the style guide title card and ID syntax was 'PointerType of null', and not the 'Uncaught type error'.

**Comment by toddmedema** [comment]
@mlan225 good catch, and thank you very much for the detailed report! Fixed with https://github.com/ExpeditionRPG/expedition-quest-creator/commit/ead09e1a9de45da6186da03e56b61c7566eb5db1
