### ISSUE TITLE
Collaborative edit jumps to last edited line on newly opened QC

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#446]
On first load and without setting the cursor anywhere in the QDL, the text update code snaps the user's view back to the beginning of the quest when a collaborator mutates the quest text.

This behavior stops once the cursor is clicked to a location.

**Comment by toddmedema** [comment]
@smartin015 seems like you and Katie were struggling a lot with this. Any further insights on how we can improve this experience as part of this fix?

**Comment by toddmedema** [comment]
This is annoying, but since we're changing this code (or removing it) soon, not worth the time
