### ISSUE TITLE
Request: Option to disallow time travel through the cards

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#449]
*Migrated to expeditionrpg/expedition#323 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

After reading this title, you should be teased "wait, WHAT???"

I just mean, the option to "go back". I really like the app, and this option for noobs players. though I'd like to create a adventure "a bit" more difficult. and this difficulty would be implemented by only disallowing the player to go back (back button) to the previous card. It would really be nice to have this kind of options

a bit like "hardcore" mode of diablo. when something is done, it's done, can't take it back

**Comment by toddmedema** [comment]
Interesting! Could certainly see it adding value from a storytelling perspective. Could either see it as a flag at the quest level (no going back as part of this quest), or for one specific card (you can't undo this decision). @ArcanaIreanol thoughts / preferences?

@smartin015 thoughts from the technical side? Seems like we should be able to read the quest or current node attribute to selectively hide the back button.

**Comment by ArcanaIreanol** [comment]
I was thinking about a full quest feature/flag

but indeed, for the "non punitive adventures", if we would be able to set that on certain cards, that would be nice

**Comment by smartin015** [comment]
Yeah, there's no reason why we couldn't add this feature at a node level (except for the added parsing complexity, but that should be low).

QDL-wise, it'd be easiest to make it available in JSON notation. I doubt people would use it often enough to warrant first-class syntax.

**Comment by smartin015** [comment]
Holding off on this for now to focus on bigger features (e.g. quest saving).
