### ISSUE TITLE
Firefox & Chrome: neither Login nor "GetStarted" buttons do anything

### ISSUE THREAD

**Issue by dneise** [ExpeditionRPG/expedition-quest-creator#456]
I just discovered Expedition. Awesome idea, did play it yet ... looking forward to a lot.

Now I wanted to have a look at the quest editor, went to https://quests.expeditiongame.com/.

Firefox (57.0.4 (64-bit) on Ubuntu 16.04)
clicked "Get Started" .. nothing happend ... tried to "Login" in the upper right corner, no luck.

Tried different browser (Google Chrome Version 58.0.3029.110 (64-bit))
Still no luck.

I also tried the "Get Started" button further down that page, also no luck.

I tried the "Expedition Home Page" button, that worked.

-----

Side notes:

* I did switch off my ad blocker in firefox, still no luck.
* The page https://quests.expeditiongame.com/ itself renders correctly as far as I can tell, everything looks nice and well. Just the buttons do not do anything.

Is there a direct link to the editor page, one could use?

**Comment by toddmedema** [comment]
@dneise good catch, fixed! (looks like our authorization library just updated versions; updating to the latest version addressed the issue)
