### ISSUE TITLE
Fix TODO on readme of this repo

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#457]
*Migrated to expeditionrpg/expedition#327 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Should actually have appropriate default config settings so new users can get started.

**Comment by toddmedema** [comment]
Backlogging given the lower than expected interest in contributions + contributors can always reach out to us directly. Updated the reaadme to state that they can reach out to us if they run into issues.
