### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#46]
- define at the top of quest with [imageName]: http://....
  - would be great if app pre-downloaded them on the start of the quest (future: offline mode, download as part of the quest cache operation)
- ability for users to upload their own images; stores it on our own server / CDN, and auto-inserts the image name tag a la above
  - question: should we resize if too large on upload? (yes)
  - question: supported file types? jpg | png | svg?

card background icons via: `* Choice name [imageName]`, `_roleplaying title_ [imageName]` etc
  - question: restrict icons to svg and png? a non-transparent JPG background would almost always end poorly
     - unless they were trying to purposefully set the entire background image, instead of just a corner icon... which would require separate CSS and some way to deliniate whether they wanted it to be a corner icon or a full background image.... perhaps `[full:name]`? Could re-use the syntax below

Full-width images
  - question: how to differentiate between inline icons and full-width images? IE if it's a map vs a symbol? Perhaps `[full:name]`?

DONE: inline images and icons via `[roll]`, `[adventurer]`, etc

**Comment by PanoramicPanda** [comment]
Might be _too_ much, but have you looked into pulling custom icons from game-icons.net?

**Comment by toddmedema** [comment]
@PanoramicPanda ooh, interesting! So, we've definitely been talking about giving creators the ability to use custom icons and images. Using a fixed source like game-icons.net could actually be a good intermediate step, since one of the challenges of allowing creators to upload their own files would be adding all of the nuances of file management .... but, if game-icons is hosting them... I'll reach out to them and see if they'd be interested in collaborating!

**Comment by PanoramicPanda** [comment]
I'm not sure if they'd allow pulling from their host, but based on the license of the site and other things I'm looking at, you could download all the icons and host them on your own. I believe I've seen a few projects that do this.

**Comment by toddmedema** [comment]
Prod updated with inline icon support! (Just the Expedition core icons for now) https://github.com/Fabricate-IO/expedition-quest-creator/pull/100

Help docs here: https://github.com/Fabricate-IO/expedition-quest-creator/blob/master/docs/icons.md

**Comment by danielwiktorczyk** [comment]
Is there any way to use the icons in the `> commands `? Effectively replacing the `[adventurer]` it uses by default. The use I'm specifically thinking of is having 

`> [d20] Each adventurer tosses a d20 `

where the d20 replaces the adventurer icon

**Comment by toddmedema** [comment]
@danielwiktorczyk PR in for replacing the default instruction icon! https://github.com/Fabricate-IO/expedition-app/pull/162

**Comment by smartin015** [comment]
Backlogging for now.

**Comment by toddmedema** [comment]
Note that we've decided not to support custom images for the foreseeable future due to technical and legal challenges, so removing this from the backlog.

In the next few months, we'll be rolling out support for a small set of crafted-for-Expedition art via https://github.com/ExpeditionRPG/expedition-app/issues/403
