### ISSUE TITLE
"Cannot read property authorize of undefined"

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#463]
This happened when resuming a concurrent edit session from a slept laptop. 

On a side note - this displayed via the snackbar, but there was no option to report it.

**Comment by toddmedema** [comment]
I don't believe the Quest Creator has click to report error functionality, so I've opened a separate issue for that: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/464
