### ISSUE TITLE
Develop a plan for Realtime API deprecation

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#465]
*Migrated to expeditionrpg/expedition#331 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Realtime API is currently in the critical path for quest creation (even when not multi-person editing) and it's scheduled to be turned down at the end of the year.

Their suggested alternative is cloud firestore, but it doesn't do any of the conflict resolution logic that made Realtime API actually useful to begin with. 

We may need to implement our own system of [operational transformation](https://www.google.com/search?q=firestore+operational+transformation&oq=firestore+operational+transformation&aqs=chrome..69i57.2744j1j1&sourceid=chrome&ie=UTF-8) on top of Firestore, postgres, or another backend in order to maintain functionality.

**Comment by smartin015** [comment]
To see whether we even want to do this, we should measure how many people are doing multi-collaborative quests. If this number is a vanishing fraction of the people editing quests, then we should just skip mult-editing.

**Comment by smartin015** [comment]
Logging will be pushed to prod soonish. Let's hold off till July/August time to see how many people use this.

**Comment by toddmedema** [comment]
Backlogging since this is an ongoing thing + Scott has a reminder
