### ISSUE TITLE
Idea: GOTO tags linkable to card location 

### ISSUE THREAD

**Issue by danielwiktorczyk** [ExpeditionRPG/expedition-quest-creator#476]
*Migrated to expeditionrpg/expedition#334 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Although you could use CTRL+F to find where you stamped the card GOTO ID #townSquare, I was thinking that a clickable link to that card within the quest creator could be a slick and quicker way to travel within the document. 

It would look like this:

```
_Town Square_ (#townSquare)

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut

* Route A 

//------------------------large chunk of code---------------------------

// somewhere along the way:

                            **goto townSquare**

* Route B

//-------------------another large chunk of code-------------------------

// somewhere along this other way, might be 200 lines down:

                            **goto townSquare**
```

In this example, any "goto townSquare" would, upon being hovered over by a mouse, display a clickable link within the document to shoot the user up to the location of the #townSquare.

**Comment by toddmedema** [comment]
I dig it! The biggest question in my mind is if Ace editor exposes an API that allows you to have custom click handlers on different pieces of text - or even lines. If that's not possible, I suppose we could also show a link icon / annotiation on the side bar on that line!

**Comment by toddmedema** [comment]
Based on a quick scan of the Ace documentation, looks like gutter links would be the much saner way to go
