### ISSUE TITLE
Better compiler errors for correct nodes w/ incorrect indentation

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#52]
*Migrated to expeditionrpg/expedition#270 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

For example, if the user indents their on win / on lose nodes in combat, should tell them to fix indentation, not that those nodes don't exist

Before throwing a "missing" error, check if its child has the thing you're looking for

**Comment by smartin015** [comment]
Backlogging - an error is better than none, and we have some of those in other bugs.
