### ISSUE TITLE
Full quest runtime checking

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#68]
Essentially, do a BFS or DFS on a rendered quest, and surface runtime errors in the IDE before people encounter them in the app. 

We'll want to track previously-seen blocks *by the scope of the previous block that led to it* so we can capture situations like:

node1 -> node 2 that modifies context -> node1

For errors, we should also capture the path that led to the error for later visualization (probably text based).

This should alert users to a vast majority of the possible runtime errors due to bad context, with the exception of counter-style loops between different nodes.

**Comment by smartin015** [comment]
Bonus: we can also detect unreachable blocks...

**Comment by toddmedema** [comment]
Another thing we can specifically check for: multiple (visible) pointers in a single block as part of detecting unreachable blocks

**Comment by toddmedema** [comment]
From in person: we can also provide a (much better) estimate of quest length than creators can, by figuring out the shortest and longest paths to end and assigning simple time estimates to each card (perhaps combat = 1 minute per tier sum, roleplaying = 1 second per word + 10 seconds per choice)

Can then make the min and max time optional. At that point, should also make min and max players optional / default to 1-6.

**Comment by smartin015** [comment]
Additionally, we can throw errors when op nodes fail (e.g. due to a variable being undefined). We could also offer suggestions (e.g. "True" and "TRUE" aren't defined variables, but "true" is a constant value)

**Comment by toddmedema** [comment]
Outstanding question: how to do we show these errors to quest creators? We'll need to show a lot of context.... Perhaps show in a modal, with a button next to it that pre-populates context, jumps you to the card, etc.... or show in gutter, but have it be clickable for more info

When does DFS get run? First, try running on spellcheck and / or save on 10x slower CPU and see if it's annoying. If too slow, perhaps when you hit publish, it shows a spinner and "validating quest", and any errors you have to resolve before publishing.

Will also help improve user syntax error catching: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/235

On release: run against the XML of all published quests. Any quests that fail should be tombstoned, and the author emailed notifying that we found a bug / that they'll need to open the QC, fix the bug and re-publish

**Comment by smartin015** [comment]
We have an E2E quest runner with actionable errors passed to the user - there's quite a few more interesting things we could surface, but this bug is done as described.
