### ISSUE TITLE
Clickable GOTO links

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#72]
*Migrated to expeditionrpg/expedition#274 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Would make it much easier to jump around the editor / find the card you're looking for

**Comment by danielwiktorcyk** [comment]
This would be great!

**Comment by toddmedema** [comment]
Possible implementation starting point. The demo is buggy / doesn't seem to work, but might be fixable: https://github.com/ajaxorg/ace/issues/1892

**Comment by smartin015** [comment]
Backlogging for now.
