### ISSUE TITLE
Offline indicator

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#86]
*Migrated to expeditionrpg/expedition#277 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

v1

* Show an "offline" indicator
  * check out how Medium's editor does it - a large, red banner drops down from the top letting the user know there was an error saving, and providing a link / button to try saving again
* Make the "Quest Saved" actually reflect that the quest wasn't saved if there's an error
* Make sure it properly resumes saving when network connection restored

v2

* use web workers to allow loading the website and caching quests & changes while offline

**Comment by toddmedema** [comment]
Ideally this would integrate with the drive api directly so that it's really "are we saving / syncing your quest right now", not "can we ping Google.com right now"

**Comment by smartin015** [comment]
Backlogging for now

**Comment by toddmedema** [comment]
Note that we do show in the UI if you're offline / save failed, but there seems to be some sort of bug around saving after you come back online - after reconnecting and making a change, it said that all changes were saved, but refreshing the page did not save those changes.
