### ISSUE TITLE
Sidebar / drawer with quest outline

### ISSUE THREAD

**Issue by danielwiktorczyk** [ExpeditionRPG/expedition-quest-creator#89]
*Migrated to expeditionrpg/expedition#278 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Something along the lines of the Google Docs sidebar that can be brought up from the left as a general time line consisting of _Titlecards_ and _combats_. In this sidebar, more information can be offered e.g. index of all variables, goto tags, enemies, etc. 

Alternatively / Additionally, allowing for branches to be collapsed into _Titlecards_ to unclutter the code, just like headings and subheadings do in Word.

**Comment by toddmedema** [comment]
Another, related idea we've been toying around with is a console (similar to the development console in Chrome) that slides up from the bottom of the screen, and lets you poke into the context, ie editing and watching variables while you're playing in the app: https://github.com/Fabricate-IO/expedition-quest-creator/issues/51

**Comment by toddmedema** [comment]
I think having the sidebar be just navigation / having the separate console for editing variables would help keep both of them easier to use and understand.

That being said, you also bring up the interesting idea of having the sidebar show more information about variables, goto tags and enemies. @danielwiktorczyk what information would you want to see? Linked line numbers for each one? Something like this?
```
var PartyFood
  _line 3_ partyFood = 0
  _line 17_ partyFood += 1

enemy Skeleton Swordsman
  _line 6_
  _line 32_
```

**Comment by danielwiktorczyk** [comment]
Yeah, something definitely along those lines, with those line links!

**Comment by smartin015** [comment]
Backlogging this for now.
